[general]
	live_config_reload=true

[window]
	decorations="None"
	padding ={x = 0, y=0}
	dynamic_padding= true
	startup_mode="Maximized"
	opacity=0.95

[font]
	normal={family="MesloLGS Nerd Font"}
	size=16
	offset={y=1}

[mouse]
	hide_when_typing=true

[colors.primary]
		background="#000000"
		foreground="#c1c1c1"

[colors.cursor]
	text="#000000"
	cursor="#c1c1c1"

[colors.vi_mode_cursor]
	text="#444444"
	cursor="#a06666"

[cursor]
	unfocused_hollow=false
