[general]
	live_config_reload=true

[window]
	decorations="Buttonless"
	padding ={x = 3, y=2}
	dynamic_padding= true
	startup_mode="Maximized"
	opacity=0.9


[font]
	normal={family="MesloLGS Nerd Font"}
	size=16
	offset={y=1}

[mouse]
	hide_when_typing=true

[cursor]
	unfocused_hollow=false

[colors.primary]
	background = "0x000000"
	foreground = "0x686868"
[colors.cursor]
	text = "0x242424"     
	cursor = "0xd8d8d8"  

[colors.normal]
black   = "0x242424" 
red     = "0xd58da2" 
green   = "0x97b0a4" 
yellow  = "0xd9a68a" 
blue    = "0x9fa6c0" 
magenta = "0xbca2b7" 
cyan    = "0xadc2c9" 
white   = "0xebe4ec" 
